"""
Django settings for typeidea project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@frf*rs56^=u2gfite1my(hdato(9@a90np%-obpk*)z+_c%yz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*",]


# Application definition
AUTH_USER_MODEL = 'user.User'  #重载用户表

INSTALLED_APPS = [
	'user',  #继承django后台用户
	'captcha', #验证码
	'silk',  #silk debug
	'debug_toolbar',   #debug工具
	'rest_framework',
	'ckeditor',  # 富文本
	'ckeditor_uploader',  #图片上传
	'dal',
	'dal_select2',
	'xadmin',
	'crispy_forms',
	'typeidea',
	'blog',
	'config',
	'comment',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
	'silk.middleware.SilkyMiddleware',
	'debug_toolbar.middleware.DebugToolbarMiddleware', #debug
	'blog.middleware.user_id.UserIDMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INTERNAL_IPS = ['127.0.0.1']  #debug 
DEBUG_TOOLBAR_CONFIG = {
	'JQUERY_URL':'https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js',
}

ROOT_URLCONF = 'typeidea.urls'

#THEME = 'default'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
       # 'DIRS': [os.path.join(BASE_DIR, 'themes', THEME, 'templates')],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'typeidea.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blog',
        'USER': 'root',
        'PASSWORD': 'Tx123456',
        'HOST': 'localhost',
        #'HOST': '172.0.0.1',
        'PORT': '3306',
		#'OPTIONS':{"unix_socket":"/tmp/mysql.sock",},
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

#TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
#修改图片的存储位置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
CKEDITOR_UPLOAD_PATH = "article_image"

#修改存储引擎
DEFAULT_FILE_STORAGE = 'typeidea.storage.WatermarkStorage'

STATICFILES_DIRS = [
#	os.path.join(BASE_DIR, 'themes', THEME, "static")
	os.path.join(BASE_DIR,  "static")
]

XADMIN_TITLE = 'foxin 管理后台'
XADMIN_FOOTER_TITLE = 'power by felix'

CKEDITOR_CONFIGS = {
	'default' : {
		'toolbar' : 'full',
		'height' : 300,
		'width' : 800,
		'tabSpaces' : 4,
		'extraPlugins' : 'codesnippet',  #配置代码插件
	},
}

REST_FRAMEWORK = {
	'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
	'PAGE_SIZE':2,
}

